kind: Role
apiVersion: v1alpha1
metadata:
  name: rt-uc.plugintemplate.halo.run-personal
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:halo-plugin-template:uc"]
    rbac.authorization.halo.run/display-name: "Halo 插件模板 UC 权限"
    rbac.authorization.halo.run/module: "Halo 插件模板"
rules:
  - apiGroups:
      - uc.plugintemplate.halo.run
    resources:
      - template-overview
    verbs:
      - get
      - list
